name: bvibank
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  blur: any
  cloud_firestore: ^5.0.2
  permission_handler: ^11.3.1
  local_auth: ^2.3.0
  google_fonts: ^6.2.1
  firebase_auth: ^5.1.1
  path_provider: any
  image_picker: ^1.1.2
  crypto: ^3.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  inapp_flutter_kyc: ^1.1.9
  image: ^4.3.0
  u_credit_card: ^1.4.0
  shared_preferences: ^2.3.3
  google_ml_kit: ^0.18.1
  camera: ^0.11.0+2
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/logo/
    - images/icons/
    - images/image/
